name: llm_dev
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - altair=6.0.0
  - annotated-types=0.7.0
  - anyio=4.11.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - astor=0.8.1
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.8
  - aws-c-common=0.12.5
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.7
  - aws-c-io=0.23.2
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.0
  - aws-sdk-cpp=1.11.606
  - babel=2.17.0
  - base58=2.1.1
  - beautifulsoup4=4.14.2
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - boto3=1.42.17
  - botocore=1.42.17
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=6.2.4
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.3
  - click=7.1.2
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.11.13
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distro=1.9.0
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - git=2.52.0
  - git-filter-repo=2.47.0
  - gitdb=4.0.12
  - gitpython=3.1.45
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.1.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - iniconfig=2.3.0
  - ipykernel=6.30.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jiter=0.12.0
  - jmespath=1.0.1
  - joblib=1.5.2
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.9
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.0
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=21.1.2
  - libcrc32c=1.1.2
  - libcurl=8.17.0
  - libdeflate=1.24
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libglib=2.86.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libparquet=22.0.0
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.2
  - libvulkan-loader=1.4.328.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.15.0
  - libxml2-16=2.15.0
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.2
  - lz4-c=1.10.0
  - markupsafe=3.0.3
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mistune=3.1.4
  - mkl=2024.2.2
  - munkres=1.1.4
  - narwhals=2.14.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - openai=2.14.0
  - openjpeg=2.5.4
  - openssl=3.6.0
  - orc=2.2.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pcre2=10.46
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.4.0
  - pluggy=1.6.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - protobuf=6.31.1
  - psutil=7.1.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pyarrow=22.0.0
  - pycparser=2.22
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pydeck=0.2.1
  - pygments=2.19.2
  - pympler=1.1
  - pyparsing=3.2.5
  - pyside6=6.9.3
  - pysocks=1.7.1
  - pytest=9.0.2
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.9.3
  - re2=2025.11.05
  - referencing=0.36.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.27.1
  - s3transfer=0.16.0
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - semver=3.0.4
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8
  - stack_data=0.6.3
  - tbb=2021.13.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tiktoken=0.12.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - tzlocal=5.3.1
  - ucrt=10.0.26100.0
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - validators=0.35.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - watchdog=6.0.0
  - wcwidth=0.2.14
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - datasets==4.1.1
      - dill==0.4.0
      - einops==0.8.1
      - filelock==3.13.1
      - frozenlist==1.8.0
      - fsspec==2024.6.1
      - huggingface-hub==0.35.3
      - inquirerpy==0.3.4
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - networkx==3.3
      - numpy==2.4.0
      - pfzy==0.3.4
      - propcache==0.4.0
      - regex==2025.9.18
      - safetensors==0.6.2
      - sentencepiece==0.2.1
      - streamlit==1.52.2
      - sympy==1.13.3
      - tokenizers==0.22.1
      - torch==2.8.0+cu129
      - torchvision==0.23.0+cu129
      - transformers==4.57.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: C:\Users\shre2\miniforge3\envs\llm_dev
